package com.geoscope.GeoEye.Space.Defines;

public final class TPolishMapFormatDefines {

	public static final int FormatID = 1;
	//.
	public static final int OBJECTKIND_UNKNOWN = 0;
	public static final int OBJECTKIND_POLYLINE = 1;
	public static final int OBJECTKIND_POLYGON = 2;
	public static final int OBJECTKIND_POI = 3;

    public static final PMFPOI[] POITypes = 
    {
        new PMFPOI(0x2c04,"<неизвестный>"),
        new PMFPOI(0x100,"Мегаполис (свыше 10 млн.)"),
        new PMFPOI(0x200,"Мегаполис (5-10 млн.)"),
        new PMFPOI(0x300,"Крупный город (2-5 млн.)"),
        new PMFPOI(0x400,"Крупный город (1-2 млн.)"),
        new PMFPOI(0x500,"Крупный город (0.5-1 млн.)"),
        new PMFPOI(0x600,"Город (200-500 тыс.)"),
        new PMFPOI(0x700,"Город (100-200 тыс.)"),
        new PMFPOI(0x800,"Город (50-100 тыс.)"),
        new PMFPOI(0x900,"Город (20-50 тыс.)"),
        new PMFPOI(0xa00,"Населенный пункт (10-20 тыс.)"),
        new PMFPOI(0xb00,"Населенный пункт (4-10 тыс.)"),
        new PMFPOI(0xc00,"Населенный пункт (2-4 тыс.)"),
        new PMFPOI(0xd00,"Населенный пункт (1-2 тыс.)"),
        new PMFPOI(0xe00,"Поселок (500-1000)"),
        new PMFPOI(0xf00,"Поселок (200-500)"),
        new PMFPOI(0x1000,"Поселок (100-200)"),
        new PMFPOI(0x1100,"Поселок (менее 100)"),
        new PMFPOI(0x1400,"Название крупного государства"),
        new PMFPOI(0x1500,"Название малого государства"),
        new PMFPOI(0x1e00,"Название области, провинции, штата"),
        new PMFPOI(0x1f00,"Название района, округа"),
        new PMFPOI(0x2800,"Надпись"),
        new PMFPOI(0x1600,"Маяк"),
        new PMFPOI(0x1601,"Туманный ревун"),
        new PMFPOI(0x1602,"Радиомаяк"),
        new PMFPOI(0x1603,"Радиобуй"),
        new PMFPOI(0x1604,"Дневной маяк (красный треугольник)"),
        new PMFPOI(0x1605,"Дневной маяк (зеленый квадрат)"),
        new PMFPOI(0x1606,"Дневной маяк (белый ромб)"),
        new PMFPOI(0x1607,"Несветящийся маяк белый"),
        new PMFPOI(0x1608,"Несветящийся маяк красный"),
        new PMFPOI(0x1609,"Несветящийся маяк зеленый"),
        new PMFPOI(0x160a,"Несветящийся маяк черный"),
        new PMFPOI(0x160b,"Несветящийся маяк желтый"),
        new PMFPOI(0x160c,"Несветящийся маяк оранжевый"),
        new PMFPOI(0x160d,"Несветящийся маяк многоцветный"),
        new PMFPOI(0x160e,"Светящийся маяк"),
        new PMFPOI(0x160f,"Светящийся маяк белый"),
        new PMFPOI(0x1610,"Светящийся маяк красный"),
        new PMFPOI(0x1611,"Светящийся маяк зеленый"),
        new PMFPOI(0x1612,"Светящийся маяк желтый"),
        new PMFPOI(0x1613,"Светящийся маяк оранжевый"),
        new PMFPOI(0x1614,"Светящийся маяк фиолетовый"),
        new PMFPOI(0x1615,"Светящийся маяк синий"),
        new PMFPOI(0x1616,"Светящийся маяк многоцветный"),
        new PMFPOI(0x1c00,"Водная преграда"),
        new PMFPOI(0x1c01,"Обломки кораблекрушения"),
        new PMFPOI(0x1c02,"Затопленные обломки, опасные"),
        new PMFPOI(0x1c03,"Затопленные обломки, не опасные"),
        new PMFPOI(0x1c04,"Обломки, очищенные драгой"),
        new PMFPOI(0x1c05,"Преграда, видимая при высокой воде"),
        new PMFPOI(0x1c06,"Преграда на уровне воды"),
        new PMFPOI(0x1c07,"Преграда ниже уровня воды"),
        new PMFPOI(0x1c08,"Преграда, очищенная драгой"),
        new PMFPOI(0x1c09,"Рифы на уровне воды"),
        new PMFPOI(0x1c0a,"Подводные рифы"),
        new PMFPOI(0x1c0b,"Отметка глубины"),
        new PMFPOI(0x1d00,"Расписание приливов"),
        new PMFPOI(0x2000,"Съезд с шоссе"),
        new PMFPOI(0x2100,"Съезд с шоссе с инфраструктурой"),
        new PMFPOI(0x210F,"Съезд к сервису"),
        new PMFPOI(0x2110,"Съезд к техобслуживанию"),
        new PMFPOI(0x2200,"Съезд к туалету"),
        new PMFPOI(0x2300,"Съезд к магазину"),
        new PMFPOI(0x2400,"Съезд к весовой станции"),
        new PMFPOI(0x2500,"Съезд платный"),
        new PMFPOI(0x2600,"Съезд к справочной"),
        new PMFPOI(0x2700,"Съезд с шоссе"),
        new PMFPOI(0x2a00,"Предприятие питания"),
        new PMFPOI(0x2a01,"Ресторан (американская кухня)"),
        new PMFPOI(0x2a02,"Ресторан (азиатская кухня)"),
        new PMFPOI(0x2a03,"Ресторан (шашлык)"),
        new PMFPOI(0x2a04,"Ресторан (китайская кухня)"),
        new PMFPOI(0x2a05,"Ресторан (деликатесы, торты, пирожные)"),
        new PMFPOI(0x2a06,"Ресторан (интернациональная кухня)"),
        new PMFPOI(0x2a07,"Ресторан быстрого питания"),
        new PMFPOI(0x2a08,"Ресторан (итальянская кухня)"),
        new PMFPOI(0x2a09,"Ресторан (мексиканская кухня)"),
        new PMFPOI(0x2a0a,"Пиццерия"),
        new PMFPOI(0x2a0b,"Ресторан (морепродукты)"),
        new PMFPOI(0x2a0c,"Ресторан (гриль)"),
        new PMFPOI(0x2a0d,"Общепит (кондитерские изделия)"),
        new PMFPOI(0x2a0e,"Кафе"),
        new PMFPOI(0x2a0f,"Ресторан (французская кухня)"),
        new PMFPOI(0x2a10,"Ресторан (немецкая кухня)"),
        new PMFPOI(0x2a11,"Ресторан (британская островная кухня)"),
        new PMFPOI(0x2a11,"Ресторан (британская островная кухня)"),
        new PMFPOI(0x2a12,"Специальные пищевые продукты"),
        new PMFPOI(0x2900,"Прочие услуги"),
        new PMFPOI(0x2b00,"Гостиница"),
        new PMFPOI(0x2b01,"Отель или мотель"),
        new PMFPOI(0x2b02,"Отель с завтраком"),
        new PMFPOI(0x2b03,"Кемпинг"),
        new PMFPOI(0x2b04,"Курортный отель"),
        new PMFPOI(0x2c00,"Объект культуры, досуга"),
        new PMFPOI(0x2c01,"ПКиО"),
        new PMFPOI(0x2c02,"Музей"),
        new PMFPOI(0x2c03,"Библиотека"),
        new PMFPOI(0x2c04,"Достопримечательность"),
        new PMFPOI(0x2c05,"Школа"),
        new PMFPOI(0x2c06,"Парк/Сад"),
        new PMFPOI(0x2c07,"Зоопарк/Аквариум"),
        new PMFPOI(0x2c08,"Стадион"),
        new PMFPOI(0x2c09,"Зал"),
        new PMFPOI(0x2c0a,"Винный ресторан"),
        new PMFPOI(0x2c0b,"Храм/Мечеть/Синагога"),
        new PMFPOI(0x2d00,"Развлекательное заведение"),
        new PMFPOI(0x2d01,"Театр"),
        new PMFPOI(0x2d02,"Бар/Ночной клуб"),
        new PMFPOI(0x2d03,"Кинотеатр"),
        new PMFPOI(0x2d04,"Казино"),
        new PMFPOI(0x2d05,"Гольф-клуб"),
        new PMFPOI(0x2d06,"Лыжный центр/курорт"),
        new PMFPOI(0x2d07,"Боулинг-центр"),
        new PMFPOI(0x2d08,"Каток"),
        new PMFPOI(0x2d09,"Бассейн"),
        new PMFPOI(0x2d0a,"Спортзал/Фитнес-центр"),
        new PMFPOI(0x2d0b,"Спортивный аэродром"),
        new PMFPOI(0x2e00,"Торговый объект"),
        new PMFPOI(0x2e01,"Универмаг"),
        new PMFPOI(0x2e02,"Бакалея"),
        new PMFPOI(0x2e03,"Торговая фирма"),
        new PMFPOI(0x2e04,"Торговый центр"),
        new PMFPOI(0x2e05,"Аптека"),
        new PMFPOI(0x2e06,"Товары повседневного спроса"),
        new PMFPOI(0x2e07,"Одежда"),
        new PMFPOI(0x2e08,"Товары для дома и сада"),
        new PMFPOI(0x2e09,"Мебель"),
        new PMFPOI(0x2e0a,"Специализированный магазин"),
        new PMFPOI(0x2e0b,"Компьютеры/ПО"),
        new PMFPOI(0x2f00,"Услуги"),
        new PMFPOI(0x2f01,"АЗС"),
        new PMFPOI(0x2f02,"Аренда автомобилей"),
        new PMFPOI(0x2f03,"Автосервис"),
        new PMFPOI(0x2f04,"Аэровокзал"),
        new PMFPOI(0x2f05,"Почтовое отделение"),
        new PMFPOI(0x2f06,"Банк"),
        new PMFPOI(0x2f07,"Автомагазин"),
        new PMFPOI(0x2f08,"Станция/остановка наземного транспорта"),
        new PMFPOI(0x2f09,"Ремонт лодок, катеров, яхт"),
        new PMFPOI(0x2f0a,"Аварийная служба, техпомощь"),
        new PMFPOI(0x2f0b,"Автостоянка"),
        new PMFPOI(0x2f0c,"Место отдыха, информация для туристов"),
        new PMFPOI(0x2f0d,"Автоклуб"),
        new PMFPOI(0x2f0e,"Автомойка"),
        new PMFPOI(0x2f0f,"Дилер фирмы Garmin"),
        new PMFPOI(0x2f10,"Служба быта (прачечная, химчистка)"),
        new PMFPOI(0x2f11,"Бизнес-сервис"),
        new PMFPOI(0x2f12,"Пункт связи"),
        new PMFPOI(0x2f13,"Бюро ремонта"),
        new PMFPOI(0x2f14,"Собес"),
        new PMFPOI(0x2f15,"Коммунальные службы"),
        new PMFPOI(0x2f16,"Стоянка грузовиков"),
        new PMFPOI(0x2f17,"Остановка общественного транспорта"),
        new PMFPOI(0x3000,"Государственная или экстренная служба"),
        new PMFPOI(0x3001,"Отделение милиции"),
        new PMFPOI(0x3002,"Больница"),
        new PMFPOI(0x3003,"Мэрия"),
        new PMFPOI(0x3004,"Суд"),
        new PMFPOI(0x3005,"Помещение для проведения общественных мероприятий"),
        new PMFPOI(0x3006,"Пограничный пункт"),
        new PMFPOI(0x3007,"Государственное учреждение"),
        new PMFPOI(0x3008,"Пожарная часть"),
        new PMFPOI(0x5900,"Аэропорт"),
        new PMFPOI(0x5901,"Крупный аэропорт"),
        new PMFPOI(0x5902,"Средний аэропорт"),
        new PMFPOI(0x5903,"Малый аэропорт"),
        new PMFPOI(0x5904,"Вертолетная площадка"),
        new PMFPOI(0x5905,"Аэропорт"),
        new PMFPOI(0x6400,"Искусственное сооружение"),
        new PMFPOI(0x6401,"Мост"),
        new PMFPOI(0x6402,"Здание"),
        new PMFPOI(0x6403,"Кладбище"),
        new PMFPOI(0x6404,"Храм/Мечеть/Синагога"),
        new PMFPOI(0x6405,"Общественное здание"),
        new PMFPOI(0x6406,"Перекресток, переправа, перевал"),
        new PMFPOI(0x6407,"Плотина"),
        new PMFPOI(0x6408,"Больница"),
        new PMFPOI(0x6409,"Плотина, набережная"),
        new PMFPOI(0x640a,"Указатель"),
        new PMFPOI(0x640b,"Военный объект"),
        new PMFPOI(0x640c,"Шахта, рудник"),
        new PMFPOI(0x640d,"Месторождение нефти"),
        new PMFPOI(0x640e,"Парк"),
        new PMFPOI(0x640f,"Почта"),
        new PMFPOI(0x6410,"Школа"),
        new PMFPOI(0x6411,"Башня, вышка"),
        new PMFPOI(0x6412,"Тропа"),
        new PMFPOI(0x6413,"Тоннель"),
        new PMFPOI(0x6414,"Питьевая вода, родник, колодец"),
        new PMFPOI(0x6415,"Заброшенное жилье"),
        new PMFPOI(0x6416,"Пристройка"),
        new PMFPOI(0x6500,"Объект гидрографии"),
        new PMFPOI(0x6501,"Арройо, высохшее русло"),
        new PMFPOI(0x6502,"Отмель"),
        new PMFPOI(0x6503,"Залив"),
        new PMFPOI(0x6504,"Излучина реки"),
        new PMFPOI(0x6505,"Искусственный канал"),
        new PMFPOI(0x6506,"Пролив"),
        new PMFPOI(0x6507,"Бухта"),
        new PMFPOI(0x6508,"Водопад"),
        new PMFPOI(0x6509,"Гейзер"),
        new PMFPOI(0x650a,"Ледник"),
        new PMFPOI(0x650b,"Гавань"),
        new PMFPOI(0x650c,"Остров"),
        new PMFPOI(0x650d,"Озеро"),
        new PMFPOI(0x650e,"Пороги"),
        new PMFPOI(0x650f,"Водохранилище"),
        new PMFPOI(0x6510,"Море"),
        new PMFPOI(0x6511,"Родник"),
        new PMFPOI(0x6512,"Ручей"),
        new PMFPOI(0x6513,"Болото"),
        new PMFPOI(0x6600,"Природный наземный объект"),
        new PMFPOI(0x6601,"Арка"),
        new PMFPOI(0x6602,"Район, область"),
        new PMFPOI(0x6603,"Котловина"),
        new PMFPOI(0x6604,"Берег"),
        new PMFPOI(0x6605,"Карниз, уступ"),
        new PMFPOI(0x6606,"Мыс"),
        new PMFPOI(0x6607,"Утес"),
        new PMFPOI(0x6608,"Кратер"),
        new PMFPOI(0x6609,"Плато"),
        new PMFPOI(0x660a,"Лес"),
        new PMFPOI(0x660b,"Ущелье, пропасть"),
        new PMFPOI(0x660c,"Узкий проход"),
        new PMFPOI(0x660d,"Перешеек"),
        new PMFPOI(0x660e,"Лава"),
        new PMFPOI(0x660f,"Столб, колонна"),
        new PMFPOI(0x6610,"Равнина"),
        new PMFPOI(0x6611,"Полигон"),
        new PMFPOI(0x6612,"Заповедник"),
        new PMFPOI(0x6613,"Хребет"),
        new PMFPOI(0x6614,"Скала"),
        new PMFPOI(0x6615,"Склон"),
        new PMFPOI(0x6616,"Вершина холма или горы"),
        new PMFPOI(0x6617,"Долина"),
        new PMFPOI(0x6618,"Лес"),
        new PMFPOI(0x5a00,"Километровый столб"),
        new PMFPOI(0x5b00,"Колокол"),
        new PMFPOI(0x5c00,"Место для дайвинга"),
        new PMFPOI(0x5d00,"Дневной знак (зеленый квадрат)"),
        new PMFPOI(0x5e00,"Дневной знак (красный треугольник)"),
        new PMFPOI(0x6000,"Громкоговоритель"),
        new PMFPOI(0x6100,"Дом"),
        new PMFPOI(0x6200,"Отметка глубины"),
        new PMFPOI(0x6300,"Отметка высоты"),
        new PMFPOI(0x4000,"Гольф-клуб"),
        new PMFPOI(0x4100,"Место для рыбалки"),
        new PMFPOI(0x4200,"Обломки, развалины"),
        new PMFPOI(0x4300,"Пристань"),
        new PMFPOI(0x4400,"АЗС"),
        new PMFPOI(0x4500,"Ресторан"),
        new PMFPOI(0x4600,"Бар"),
        new PMFPOI(0x4700,"Лодочный причал"),
        new PMFPOI(0x4800,"Кемпинг"),
        new PMFPOI(0x4900,"Парк"),
        new PMFPOI(0x4a00,"Место для пикника"),
        new PMFPOI(0x4b00,"Медпункт"),
        new PMFPOI(0x4c00,"Справочная"),
        new PMFPOI(0x4d00,"Автостоянка"),
        new PMFPOI(0x4e00,"Туалет"),
        new PMFPOI(0x4f00,"Душ"),
        new PMFPOI(0x5000,"Питьевая вода"),
        new PMFPOI(0x5100,"Телефон"),
        new PMFPOI(0x5200,"Красивый вид"),
        new PMFPOI(0x5300,"Лыжная база"),
        new PMFPOI(0x5400,"Место для купания"),
        new PMFPOI(0x5500,"Дамба, плотина"),
        new PMFPOI(0x5600,"Запретная зона"),
        new PMFPOI(0x5700,"Опасная зона"),
        new PMFPOI(0x5800,"Ограниченный доступ")
    };
    
    public static String GetObjectTypeName(int KindID, int TypeID) {
    	switch (KindID) {
    	case OBJECTKIND_POI:
    		for (int I = 0; I < POITypes.length; I++)
    			if (POITypes[I].TypeID == TypeID)
    				return POITypes[I].TypeName;
    		return ""; //. ->
    		
    	default:
    		return ""; //. ->
    	}
    }
}
